spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapidemo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass
